name: hook_controller
description: >-
  Simple hooks system, used to modify value or the context of specific type
  by series of hooks, each one gets the previous value and the commit method to
  apply changes.
repository: https://github.com/Davenchy/hook_controller
version: 1.1.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  lints: ^1.0.1
